import { jsPDF } from "jspdf";
import type { IssueCategory } from "@/lib/categories";
import { CATEGORY_MAP, STATUS_LABEL } from "@/lib/categories";

export type HandoffIssue = {
  id: string;
  title: string;
  description: string | null;
  category: IssueCategory;
  status: "open" | "acknowledged" | "fixed";
  lat: number;
  lng: number;
  upvote_count: number;
  created_at: string;
};

// A brief italic note appended to a handed-off issue so neighbors know it's
// escalated. Kept short and constructive.
export const HANDOFF_NOTE =
  "Handed off to a verified city-hall moderator — the request has been logged and forwarded to the responsible department. Neighbors will see the status here as it moves.";

// Compose a 311-style plain-text email body for city officials.
export function build311EmailBody(issue: HandoffIssue, community: string, senderOrg: string): string {
  const cat = CATEGORY_MAP[issue.category]?.label ?? issue.category;
  const mapUrl = `https://www.openstreetmap.org/?mlat=${issue.lat}&mlon=${issue.lng}#map=19/${issue.lat}/${issue.lng}`;
  return [
    `Subject: [BlockBeacon] ${cat} — ${issue.title}`,
    ``,
    `Hello,`,
    ``,
    `A resident-reported issue in ${community} has reached ${issue.upvote_count} community upvote${issue.upvote_count === 1 ? "" : "s"} and is being handed off for review.`,
    ``,
    `Category: ${cat}`,
    `Current status: ${STATUS_LABEL[issue.status]}`,
    `Reported: ${new Date(issue.created_at).toLocaleString()}`,
    `Location: ${issue.lat.toFixed(6)}, ${issue.lng.toFixed(6)}`,
    `Map: ${mapUrl}`,
    ``,
    `Description:`,
    (issue.description ?? "(No additional details)"),
    ``,
    `This message was compiled from BlockBeacon and forwarded by ${senderOrg}.`,
    `Reference ID: ${issue.id}`,
  ].join("\n");
}

// Client-side PDF builder for the same 311-style document, so the moderator
// can attach it or archive it. Returns a Blob URL for download.
export function buildHandoffPdf(issue: HandoffIssue, community: string, senderOrg: string): { url: string; filename: string } {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const cat = CATEGORY_MAP[issue.category]?.label ?? issue.category;
  const marginX = 56;
  let y = 72;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Community Issue Handoff — 311 Referral", marginX, y);
  y += 26;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Prepared by ${senderOrg} · BlockBeacon`, marginX, y);
  y += 20;
  doc.setTextColor(30);

  const rows: Array<[string, string]> = [
    ["Community", community],
    ["Category", cat],
    ["Title", issue.title],
    ["Current status", STATUS_LABEL[issue.status]],
    ["Upvotes", String(issue.upvote_count)],
    ["Reported", new Date(issue.created_at).toLocaleString()],
    ["Location", `${issue.lat.toFixed(6)}, ${issue.lng.toFixed(6)}`],
    ["Reference ID", issue.id],
  ];

  doc.setFontSize(11);
  for (const [k, v] of rows) {
    doc.setFont("helvetica", "bold");
    doc.text(`${k}:`, marginX, y);
    doc.setFont("helvetica", "normal");
    const wrapped = doc.splitTextToSize(v, 400);
    doc.text(wrapped, marginX + 96, y);
    y += Math.max(16, wrapped.length * 14);
  }

  y += 12;
  doc.setFont("helvetica", "bold");
  doc.text("Description", marginX, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  const desc = doc.splitTextToSize(issue.description ?? "(No additional details)", 500);
  doc.text(desc, marginX, y);
  y += desc.length * 14 + 24;

  doc.setDrawColor(200);
  doc.line(marginX, y, marginX + 500, y);
  y += 18;
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text("Generated by BlockBeacon. Neighbors will continue to see updates in the app.", marginX, y);

  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  return { url, filename: `blockbeacon-handoff-${issue.id.slice(0, 8)}.pdf` };
}